version: "3.8"

services:

  server:
    image: ${DOCKER_REGISTRY}/test-server:v1.5.0
    build:
      context: .
      dockerfile: ./tools/docker/php/Dockerfile
    container_name: test-server
    environment:
      BDD_VERSION: ${DB_VERSION:-5.7}
      BDD_TYPE: ${DB_TYPE:-mysql}
      BDD_HOST: ${DB_HOST:-mysql}
      BDD_PORT: ${DB_PORT:-3306}
      BDD_CHARSET: ${DB_CHARSET:-utf8mb4}
      BDD_USER: ${DB_USER:-user}
      BDD_PASSWORD: ${DB_PASSWORD:-resu}
      BDD_DATABASE: ${DB_DATABASE:-app}
    volumes:
      - ./:/var/www/html:rw
    labels:
      - "traefik.http.routers.test-server.rule=Host(`test-docker-symfony.traefik.me`)"
      - "traefik.http.routers.test-server-tls.tls.domains[0].main=test-docker-symfony.traefik.me"
      - "traefik.http.routers.test-server-tls.tls.domains[0].sans=test-docker-symfony-*.traefik.me"
      - "traefik.http.services.test-server.loadbalancer.server.port=80"
      - "traefik.http.routers.test-server.tls=true"
    links:
      - mysql
      - redis

  adminer:
    image: ${DOCKER_REGISTRY}/test-adminer:v1.0.0
    build:
      context: .
      dockerfile: ./tools/docker/adminer/Dockerfile
    container_name: test-adminer
    ports:
      - 8080:8080
    volumes:
      - ./var/db:/var/www/html/var/db:rw

  mysql:
    image: mysql:${DB_VERSION:-8.3}
    container_name: test-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-toor}
      MYSQL_DATABASE: ${DB_DATABASE:-app}
      MYSQL_USER: ${DB_USER:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-resu}
    ports:
      - ${DB_PORT}:${DB_PORT}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: test-phpmyadmin
    environment:
      - PMA_HOST=${DB_HOST:-mysql}
      - PMA_USER=root
      - PMA_PASSWORD=${DB_ROOT_PASSWORD:-toor}
    links:
      - mysql
    ports:
      - 8090:80

  mailer:
    image: schickling/mailcatcher
    container_name: test-mailcatcher
    ports: 
      - 1025:1025
      - 1080:1080
  
  redis:
    image: redis
    container_name: test-redis
    ports:
      - 6379:6379

  traefik:
    image: traefik:v2.0.2
    container_name: test-traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - 8081:8080
    labels:
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    volumes:
      - ./tools/docker/traefik/traefik.yml:/etc/traefik/traefik.yml:rw
      - ./tools/docker/traefik/tls.yml:/etc/traefik/tls.yml:rw
      - /var/run/docker.sock:/var/run/docker.sock
      - certs:/etc/ssl/traefik:rw

  reverse-proxy-https-helper:
    image: alpine
    container_name: test-reverse-proxy
    command: sh -c "cd /etc/ssl/traefik
      && wget traefik.me/cert.pem -O cert.pem
      && wget traefik.me/privkey.pem -O privkey.pem"
    volumes:
      - certs:/etc/ssl/traefik:rw

volumes:
  certs:
