controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# app_index:
#     path: /index/test
#     controller: App\Controller\IndexController::test