name: Run tests

on:
  workflow_dispatch:
  push:
    #branches: [ "main" ]
  pull_request:
    #branches: [ "main" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    
    - uses: actions/checkout@v3

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --prefer-dist

    - name: Create Database
      run: |
        mkdir -p var/db
        touch var/db/app_test.db
        bin/console doctrine:migration:migrate --env=test -q

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: bin/phpunit
